version: '3.8'

services:
  # 前端应用
  realtime-frontend:
    image: gghtrt520/chat:latest
    pull_policy: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NODE_ENV=production
      - DOMAIN=${DOMAIN}
      - CADDY_EMAIL=${CADDY_EMAIL}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - realtime-network
    volumes:
      - ./data:/data
      - ./data/caddy:/root/.local/share/caddy

networks:
  realtime-network:
    driver: bridge